//"nn bb ss u primitive data types")
let a=null;
let b=20;
var c=false// also be true
let d=BigInt("567")+BigInt("3")
let e="tanu";
let f=Symbol("I am a nice symbol")
let g=undefined
let h=
console.log(a,b,c,d,e,f,g)
console.log(typeof d)
console.log(typeof c)
console.log(typeof h)

//Objects in JS
const item ={
  "thakre":true,
  "sonal":false,
  "pragati":80,
  "ranu": undefined 
}
console.log(item["sonal"])
